### ISSUE TITLE
go pluralize v0.1.4 in here too

### ISSUE THREAD

**Issue by troian** [web-ridge/sqlboiler-graphql-schema#5]
https://github.com/web-ridge/sqlboiler-graphql-schema/blob/34d42dfecb77aad006ffd82201eb43f7b3cdf7a4/go.mod#L6

**Comment by RichardLindhout** [comment]
Fixed in new release!

**Comment by troian** [comment]
Needs go mod tidy to run

github.com/web-ridge/sqlboiler-graphql-schema imports
    github.com/gertd/go-pluralize: github.com/gertd/go-pluralize@v0.1.2: verifying module: checksum mismatch
    downloaded: h1:8q9mYRD4K9X6fsldYCQKM3HZtNV/gfieh6xerucwoM4=
    sum.golang.org: h1:3aljIkBHcMFPYdveAiihVWZ+7ZH2ALkRgJw0YPqqCrk=

**Comment by RichardLindhout** [comment]
Should be fixed now!

**Comment by RichardLindhout** [comment]
Let me know if it works so I can close the issue :)

**Comment by troian** [comment]
Works now

**Comment by troian** [comment]
I was a bit optimistic.
It still gives an error
```
go generate
go: finding module for package github.com/web-ridge/sqlboiler-graphql-schema
go: found github.com/web-ridge/sqlboiler-graphql-schema in github.com/web-ridge/sqlboiler-graphql-schema v1.0.2
go: downloading github.com/web-ridge/gqlgen-sqlboiler/v2 v2.0.5
github.com/gertd/go-pluralize@v0.1.2: verifying module: checksum mismatch
    downloaded: h1:8q9mYRD4K9X6fsldYCQKM3HZtNV/gfieh6xerucwoM4=
    sum.golang.org: h1:3aljIkBHcMFPYdveAiihVWZ+7ZH2ALkRgJw0YPqqCrk=
```

**Comment by RichardLindhout** [comment]
Haha wut same as this https://github.com/gertd/go-pluralize/issues/8

**Comment by RichardLindhout** [comment]
Ok. I've forked https://github.com/web-ridge/go-pluralize. And upgraded gqlgen-sqlboiler and sqlboiler-graphql-schema.

**Comment by RichardLindhout** [comment]
https://github.com/web-ridge/sqlboiler-graphql-schema/releases -> v1.0.3
https://github.com/web-ridge/gqlgen-sqlboiler/releases -> v2.0.6
